/**
 * Project SEAF - Centralized Configuration
 * 모든 설정과 템플릿, 카테고리 데이터를 중앙 관리합니다.
 */

const SEAF_CONFIG = {
  MANGHO_HEAD_ID: "60",
  NOTI_DURATION: 6000,
  
  // 제목 및 본문 템플릿
  TEMPLATES: {
    title: "{emoji} {target} {diff} 망호 모집",
    content: "{lobby_image_html}<br>{custom_content}<br><br><i>Generated by SEAF Assistant</i>"
  },

  // 난이도 공통 데이터 (1단 ~ 10단)
  DIFFICULTIES: Array.from({ length: 10 }, (_, i) => (i + 1).toString()),

  // 대분류 및 귀속 태그 정의 (유동적 UI 생성용)
  CATEGORIES: {
    TERMINID: {
      name: "테르미니드",
      emoji: "🪳",
      color: "#EAD033",
      tags: ["프레데터", "럽쳐", "글룸", "하이브월드", "하이브로드"],
      hasDifficulty: true
    },
    AUTOMATON: {
      name: "오토마톤",
      emoji: "🤖",
      color: "#FF4500",
      tags: ["소각대", "제트여단"],
      hasDifficulty: true
    },
    ILLUMINATE: {
      name: "일루미닛",
      emoji: "🦑",
      color: "#931bca",
      tags: ["스쿼드", "오벨리스크"],
      hasDifficulty: true
    },
    ANYWHERE: {
      name: "아무데나",
      emoji: "🗺️",
      color: "#FFFFFF",
      tags: [],
      hasDifficulty: true
    },
    CREDIT_RUN: {
      name: "크레딧런",
      emoji: "💎",
      color: "#006eff",
      tags: [],
      hasDifficulty: false // 크레딧런은 난이도 선택 불필요
    }
  }
};